project:
  type: book

book:
  title: "R Programming Notes"
  author: "Kittipos Sirivongrungson"
  date: "4/16/2022" # `today` for current date when render
  site-url: https://r-programming-lightbridge.netlify.app
  repo-url: https://github.com/Lightbridge-KS/r-programming-notes
  chapters:
    - index.qmd
    - vector.qmd
    - ctr-flow.qmd
    - function.qmd
    - rlang.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    number-sections: false
    code-link: true
  #pdf:
    #documentclass: scrreprt


# freeze computational output ? (see: https://quarto.org/docs/projects/code-execution.html#freeze)
freeze: auto



